name: Deploy to Azure

on:
 push:
   branches:
     - main
jobs:
 build-and-deploy:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Azure
      uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Log in to Azure Container Registry
      env:
        ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
        ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
      run: echo "$ACR_PASSWORD" | docker login rolregistrydev.azurecr.io -u "$ACR_USERNAME" --password-stdin

    - name: Build and push Docker image
      run: |
          docker build -t rolwebapp:v1 -f RoLWebApp/Dockerfile RoLWebApp/
          docker tag rolwebapp:v1 rolregistrydev.azurecr.io/rolwebapp:v1
          docker push rolregistrydev.azurecr.io/rolwebapp:v1

    - name: Update Azure Web App container
      run: |
          az webapp config container set \
            --name RoL-containerwebapp \
            --resource-group <your-resource-group> \
            --docker-custom-image-name rolregistrydev.azurecr.io/rolwebapp:v1 \
            --docker-registry-server-url https://rolregistrydev.azurecr.io
